version: "3"

services:
  mshare_web_app:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'npm run dev'
    ports:
      - "3000:3000"
    tty: true
    container_name: mshare_web_app
